language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

os:
    - windows
    - linux

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - eval "$(~/*conda*/bin/conda shell.bash hook)"
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

matrix:
    allow_failures:
        - python: "3.7-dev"

# command to install dependencies
install:
    - pip install pipenv
    - pipenv install '-e .' --skip-lock --ignore-pipfile
    - pipenv install --dev --skip-lock

# command to run tests
script: pipenv run pytest tests/
